version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: weather
      POSTGRES_USER: weatherHouse
      POSTGRES_PASSWORD: weatherHousePass123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - weather_house_network
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: candoga01@gmail.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "8789:80"
    depends_on:
      - postgres
    restart: always
    networks:
      - weather_house_network

volumes:
  postgres_data:

networks:
  weather_house_network:
    driver: bridge
